"""add file_path to cvs

Revision ID: 28700b089843
Revises: 46e3c3c979e5
Create Date: 2026-10-05 22:57:10.200500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28700b089843'
down_revision: Union[str, Sequence[str], None] = '46e3c3c979e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cvs', sa.Column('file_path', sa.String(), nullable=True))
    op.alter_column('cvs', 'label',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cvs', 'label',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cvs', 'file_path')
    # ### end Alembic commands ###
