"""add deleted_at to cvs

Revision ID: 3e450f529e0f
Revises: 28700b089843
Create Date: 2026-10-07 07:13:16.374231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e450f529e0f'
down_revision: Union[str, Sequence[str], None] = '28700b089843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cvs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cvs', 'deleted_at')
    # ### end Alembic commands ###
